exclude: ^(examples)

ci:
  autoupdate_schedule: weekly
  skip: [mypy, pyright]
  autofix_commit_msg: pre-commit auto-fixes
  autoupdate_commit_msg: pre-commit autoupdate

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types:
          - "json"
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.359
    hooks:
    - id: pyright
      additional_dependencies: ["numpy", "scipy", "matplotlib", "PySide6", "PyOpenGL", "pytest", "pytest-qt", "pyrr"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        stages: [commit, commit-msg]
        additional_dependencies: [tomli] # read pyproject.toml below py3.11

  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.16.2
    hooks:
      - id: cython-lint
        args: [--no-pycodestyle]
      - id: double-quote-cython-strings
