# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mos_dialog.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDialog, QDoubleSpinBox,
    QFrame, QHeaderView, QLabel, QPushButton,
    QSizePolicy, QSpinBox, QTabWidget, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MOs_dialog(object):
    def setupUi(self, MOs_dialog):
        if not MOs_dialog.objectName():
            MOs_dialog.setObjectName(u"MOs_dialog")
        MOs_dialog.resize(591, 302)
        self.normalizationFrame = QFrame(MOs_dialog)
        self.normalizationFrame.setObjectName(u"normalizationFrame")
        self.normalizationFrame.setGeometry(QRect(210, 160, 211, 140))
        self.normalizationFrame.setFrameShape(QFrame.StyledPanel)
        self.normalizationFrame.setFrameShadow(QFrame.Raised)
        self.label_2 = QLabel(self.normalizationFrame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 40, 131, 20))
        self.label_8 = QLabel(self.normalizationFrame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 80, 161, 20))
        self.exactCountLabel = QLabel(self.normalizationFrame)
        self.exactCountLabel.setObjectName(u"exactCountLabel")
        self.exactCountLabel.setGeometry(QRect(10, 60, 131, 20))
        self.normalizationButton = QPushButton(self.normalizationFrame)
        self.normalizationButton.setObjectName(u"normalizationButton")
        self.normalizationButton.setGeometry(QRect(10, 10, 190, 32))
        self.normalizationButton.setAutoDefault(False)
        self.calculatedCountLabel = QLabel(self.normalizationFrame)
        self.calculatedCountLabel.setObjectName(u"calculatedCountLabel")
        self.calculatedCountLabel.setGeometry(QRect(10, 100, 131, 20))
        self.molecularOrbitalFrame = QFrame(MOs_dialog)
        self.molecularOrbitalFrame.setObjectName(u"molecularOrbitalFrame")
        self.molecularOrbitalFrame.setGeometry(QRect(0, 0, 211, 300))
        self.molecularOrbitalFrame.setFrameShape(QFrame.StyledPanel)
        self.molecularOrbitalFrame.setFrameShadow(QFrame.Raised)
        self.orbitalSelector = QTableWidget(self.molecularOrbitalFrame)
        self.orbitalSelector.setObjectName(u"orbitalSelector")
        self.orbitalSelector.setGeometry(QRect(10, 70, 191, 220))
        self.orbTypeLabel = QLabel(self.molecularOrbitalFrame)
        self.orbTypeLabel.setObjectName(u"orbTypeLabel")
        self.orbTypeLabel.setGeometry(QRect(90, 10, 101, 16))
        self.orbTypeLabel.setMaximumSize(QSize(101, 16))
        self.label = QLabel(self.molecularOrbitalFrame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 81, 16))
        self.betaCheckBox = QCheckBox(self.molecularOrbitalFrame)
        self.betaCheckBox.setObjectName(u"betaCheckBox")
        self.betaCheckBox.setGeometry(QRect(150, 30, 61, 20))
        self.alphaCheckBox = QCheckBox(self.molecularOrbitalFrame)
        self.alphaCheckBox.setObjectName(u"alphaCheckBox")
        self.alphaCheckBox.setGeometry(QRect(90, 30, 61, 21))
        self.restrictedLabel = QLabel(self.molecularOrbitalFrame)
        self.restrictedLabel.setObjectName(u"restrictedLabel")
        self.restrictedLabel.setGeometry(QRect(90, 30, 61, 16))
        self.label_3 = QLabel(self.molecularOrbitalFrame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 50, 91, 16))
        self.label_7 = QLabel(self.molecularOrbitalFrame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 30, 91, 16))
        self.generalFrame = QFrame(MOs_dialog)
        self.generalFrame.setObjectName(u"generalFrame")
        self.generalFrame.setGeometry(QRect(210, 0, 211, 161))
        self.generalFrame.setFrameShape(QFrame.StyledPanel)
        self.generalFrame.setFrameShadow(QFrame.Raised)
        self.label_10 = QLabel(self.generalFrame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(110, 10, 27, 16))
        self.cutoffSpinBox = QDoubleSpinBox(self.generalFrame)
        self.cutoffSpinBox.setObjectName(u"cutoffSpinBox")
        self.cutoffSpinBox.setGeometry(QRect(140, 10, 65, 22))
        self.cutoffSpinBox.setDecimals(2)
        self.cutoffSpinBox.setMinimum(-15.000000000000000)
        self.cutoffSpinBox.setMaximum(-2.000000000000000)
        self.cutoffSpinBox.setSingleStep(0.100000000000000)
        self.cutoffSpinBox.setValue(-3.500000000000000)
        self.label_9 = QLabel(self.generalFrame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 10, 101, 16))
        self.colorMinusButton = QPushButton(self.generalFrame)
        self.colorMinusButton.setObjectName(u"colorMinusButton")
        self.colorMinusButton.setGeometry(QRect(90, 100, 100, 32))
        self.colorPlusButton = QPushButton(self.generalFrame)
        self.colorPlusButton.setObjectName(u"colorPlusButton")
        self.colorPlusButton.setGeometry(QRect(90, 60, 100, 32))
        self.label_11 = QLabel(self.generalFrame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 70, 58, 16))
        self.label_12 = QLabel(self.generalFrame)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 110, 58, 16))
        self.isoTab = QTabWidget(MOs_dialog)
        self.isoTab.setObjectName(u"isoTab")
        self.isoTab.setGeometry(QRect(420, 0, 171, 241))
        self.isosurfaceTab = QWidget()
        self.isosurfaceTab.setObjectName(u"isosurfaceTab")
        self.isosurfaceFrame = QFrame(self.isosurfaceTab)
        self.isosurfaceFrame.setObjectName(u"isosurfaceFrame")
        self.isosurfaceFrame.setGeometry(QRect(0, 0, 161, 201))
        self.isosurfaceFrame.setFrameShape(QFrame.StyledPanel)
        self.isosurfaceFrame.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.isosurfaceFrame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 91, 16))
        self.cubeBoxSizeSpinBox = QDoubleSpinBox(self.isosurfaceFrame)
        self.cubeBoxSizeSpinBox.setObjectName(u"cubeBoxSizeSpinBox")
        self.cubeBoxSizeSpinBox.setGeometry(QRect(90, 10, 65, 22))
        self.cubeBoxSizeSpinBox.setDecimals(1)
        self.cubeBoxSizeSpinBox.setMinimum(-1.900000000000000)
        self.cubeBoxSizeSpinBox.setMaximum(20.000000000000000)
        self.cubeBoxSizeSpinBox.setSingleStep(0.100000000000000)
        self.cubeBoxSizeSpinBox.setValue(0.000000000000000)
        self.checkBoxWireMesh = QCheckBox(self.isosurfaceFrame)
        self.checkBoxWireMesh.setObjectName(u"checkBoxWireMesh")
        self.checkBoxWireMesh.setGeometry(QRect(10, 130, 85, 20))
        self.toggleDisplayBoxButton = QPushButton(self.isosurfaceFrame)
        self.toggleDisplayBoxButton.setObjectName(u"toggleDisplayBoxButton")
        self.toggleDisplayBoxButton.setGeometry(QRect(10, 90, 140, 32))
        self.toggleDisplayBoxButton.setAutoDefault(False)
        self.displayMos = QPushButton(self.isosurfaceFrame)
        self.displayMos.setObjectName(u"displayMos")
        self.displayMos.setGeometry(QRect(10, 160, 140, 32))
        self.displayMos.setAutoDefault(False)
        self.isoValueSpinBox = QDoubleSpinBox(self.isosurfaceFrame)
        self.isoValueSpinBox.setObjectName(u"isoValueSpinBox")
        self.isoValueSpinBox.setGeometry(QRect(90, 70, 65, 22))
        self.isoValueSpinBox.setDecimals(4)
        self.isoValueSpinBox.setMinimum(0.000100000000000)
        self.isoValueSpinBox.setMaximum(1.000000000000000)
        self.isoValueSpinBox.setSingleStep(0.005000000000000)
        self.isoValueSpinBox.setValue(0.200000000000000)
        self.label_6 = QLabel(self.isosurfaceFrame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 70, 91, 16))
        self.label_5 = QLabel(self.isosurfaceFrame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 40, 91, 16))
        self.voxelSizeSpinBox = QDoubleSpinBox(self.isosurfaceFrame)
        self.voxelSizeSpinBox.setObjectName(u"voxelSizeSpinBox")
        self.voxelSizeSpinBox.setGeometry(QRect(90, 40, 65, 22))
        self.voxelSizeSpinBox.setDecimals(2)
        self.voxelSizeSpinBox.setMinimum(0.050000000000000)
        self.voxelSizeSpinBox.setMaximum(1.000000000000000)
        self.voxelSizeSpinBox.setSingleStep(0.050000000000000)
        self.voxelSizeSpinBox.setValue(0.200000000000000)
        self.isoTab.addTab(self.isosurfaceTab, "")
        self.isolineTab = QWidget()
        self.isolineTab.setObjectName(u"isolineTab")
        self.isoLineFrame = QFrame(self.isolineTab)
        self.isoLineFrame.setObjectName(u"isoLineFrame")
        self.isoLineFrame.setGeometry(QRect(0, 0, 161, 211))
        self.isoLineFrame.setFrameShape(QFrame.StyledPanel)
        self.isoLineFrame.setFrameShadow(QFrame.Raised)
        self.numberLinesSpinBox = QSpinBox(self.isoLineFrame)
        self.numberLinesSpinBox.setObjectName(u"numberLinesSpinBox")
        self.numberLinesSpinBox.setGeometry(QRect(110, 10, 42, 22))
        self.numberLinesSpinBox.setMinimum(3)
        self.numberLinesSpinBox.setMaximum(20)
        self.numberLinesSpinBox.setValue(10)
        self.label_13 = QLabel(self.isoLineFrame)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 10, 70, 16))
        self.displayIsolinesButton = QPushButton(self.isoLineFrame)
        self.displayIsolinesButton.setObjectName(u"displayIsolinesButton")
        self.displayIsolinesButton.setGeometry(QRect(10, 70, 140, 32))
        self.label_14 = QLabel(self.isoLineFrame)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 40, 70, 16))
        self.isolineVoxelSizeSpinBox = QDoubleSpinBox(self.isoLineFrame)
        self.isolineVoxelSizeSpinBox.setObjectName(u"isolineVoxelSizeSpinBox")
        self.isolineVoxelSizeSpinBox.setGeometry(QRect(90, 40, 62, 22))
        self.isolineVoxelSizeSpinBox.setMinimum(0.030000000000000)
        self.isolineVoxelSizeSpinBox.setMaximum(0.500000000000000)
        self.isolineVoxelSizeSpinBox.setSingleStep(0.010000000000000)
        self.isolineVoxelSizeSpinBox.setValue(0.050000000000000)
        self.isoTab.addTab(self.isolineTab, "")

        self.retranslateUi(MOs_dialog)

        self.isoTab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MOs_dialog)
    # setupUi

    def retranslateUi(self, MOs_dialog):
        MOs_dialog.setWindowTitle(QCoreApplication.translate("MOs_dialog", u"Orbitals", None))
        self.label_2.setText(QCoreApplication.translate("MOs_dialog", u"Exact Electroncount:", None))
        self.label_8.setText(QCoreApplication.translate("MOs_dialog", u"Calculated Electroncount:", None))
        self.exactCountLabel.setText("")
        self.normalizationButton.setText(QCoreApplication.translate("MOs_dialog", u"Check Normalization", None))
        self.calculatedCountLabel.setText("")
        self.orbTypeLabel.setText(QCoreApplication.translate("MOs_dialog", u"Cartesian", None))
        self.label.setText(QCoreApplication.translate("MOs_dialog", u"Orbital type:", None))
        self.betaCheckBox.setText(QCoreApplication.translate("MOs_dialog", u"Beta", None))
        self.alphaCheckBox.setText(QCoreApplication.translate("MOs_dialog", u"Alpha", None))
        self.restrictedLabel.setText(QCoreApplication.translate("MOs_dialog", u"Restricted", None))
        self.label_3.setText(QCoreApplication.translate("MOs_dialog", u"Select Orbital:", None))
        self.label_7.setText(QCoreApplication.translate("MOs_dialog", u"Select Spin:", None))
        self.label_10.setText(QCoreApplication.translate("MOs_dialog", u"10 ^", None))
        self.label_9.setText(QCoreApplication.translate("MOs_dialog", u"Distance Cutoff:", None))
        self.colorMinusButton.setText(QCoreApplication.translate("MOs_dialog", u"Select", None))
        self.colorPlusButton.setText(QCoreApplication.translate("MOs_dialog", u"Select", None))
        self.label_11.setText(QCoreApplication.translate("MOs_dialog", u"Color +", None))
        self.label_12.setText(QCoreApplication.translate("MOs_dialog", u"Color -", None))
        self.label_4.setText(QCoreApplication.translate("MOs_dialog", u"Box Size", None))
        self.checkBoxWireMesh.setText(QCoreApplication.translate("MOs_dialog", u"Wire Mesh", None))
        self.toggleDisplayBoxButton.setText(QCoreApplication.translate("MOs_dialog", u"Display Box", None))
        self.displayMos.setText(QCoreApplication.translate("MOs_dialog", u"Display Orbital", None))
        self.label_6.setText(QCoreApplication.translate("MOs_dialog", u"Isovalue:", None))
        self.label_5.setText(QCoreApplication.translate("MOs_dialog", u"Voxel Size:", None))
        self.isoTab.setTabText(self.isoTab.indexOf(self.isosurfaceTab), QCoreApplication.translate("MOs_dialog", u"Isosurface", None))
        self.label_13.setText(QCoreApplication.translate("MOs_dialog", u"# of Lines:", None))
        self.displayIsolinesButton.setText(QCoreApplication.translate("MOs_dialog", u"Display Isolines", None))
        self.label_14.setText(QCoreApplication.translate("MOs_dialog", u"Voxel Size:", None))
        self.isoTab.setTabText(self.isoTab.indexOf(self.isolineTab), QCoreApplication.translate("MOs_dialog", u"Isolines", None))
    # retranslateUi
