# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mos_dialog.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDialog, QDoubleSpinBox,
    QFrame, QHeaderView, QLabel, QPushButton,
    QSizePolicy, QSpinBox, QTabWidget, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MOs_dialog(object):
    def setupUi(self, MOs_dialog):
        if not MOs_dialog.objectName():
            MOs_dialog.setObjectName(u"MOs_dialog")
        MOs_dialog.resize(384, 414)
        self.molecularOrbitalFrame = QFrame(MOs_dialog)
        self.molecularOrbitalFrame.setObjectName(u"molecularOrbitalFrame")
        self.molecularOrbitalFrame.setGeometry(QRect(0, 0, 211, 291))
        self.molecularOrbitalFrame.setFrameShape(QFrame.StyledPanel)
        self.molecularOrbitalFrame.setFrameShadow(QFrame.Raised)
        self.orbitalSelector = QTableWidget(self.molecularOrbitalFrame)
        self.orbitalSelector.setObjectName(u"orbitalSelector")
        self.orbitalSelector.setGeometry(QRect(10, 70, 191, 211))
        self.orbTypeLabel = QLabel(self.molecularOrbitalFrame)
        self.orbTypeLabel.setObjectName(u"orbTypeLabel")
        self.orbTypeLabel.setGeometry(QRect(90, 10, 101, 16))
        self.orbTypeLabel.setMaximumSize(QSize(101, 16))
        self.label = QLabel(self.molecularOrbitalFrame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 81, 16))
        self.betaCheckBox = QCheckBox(self.molecularOrbitalFrame)
        self.betaCheckBox.setObjectName(u"betaCheckBox")
        self.betaCheckBox.setGeometry(QRect(150, 30, 61, 20))
        self.alphaCheckBox = QCheckBox(self.molecularOrbitalFrame)
        self.alphaCheckBox.setObjectName(u"alphaCheckBox")
        self.alphaCheckBox.setGeometry(QRect(90, 30, 61, 21))
        self.restrictedLabel = QLabel(self.molecularOrbitalFrame)
        self.restrictedLabel.setObjectName(u"restrictedLabel")
        self.restrictedLabel.setGeometry(QRect(90, 30, 61, 16))
        self.label_3 = QLabel(self.molecularOrbitalFrame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 50, 91, 16))
        self.label_7 = QLabel(self.molecularOrbitalFrame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 30, 91, 16))
        self.generalFrame = QFrame(MOs_dialog)
        self.generalFrame.setObjectName(u"generalFrame")
        self.generalFrame.setGeometry(QRect(0, 290, 211, 120))
        self.generalFrame.setFrameShape(QFrame.StyledPanel)
        self.generalFrame.setFrameShadow(QFrame.Raised)
        self.label_10 = QLabel(self.generalFrame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(110, 10, 27, 16))
        self.cutoffSpinBox = QDoubleSpinBox(self.generalFrame)
        self.cutoffSpinBox.setObjectName(u"cutoffSpinBox")
        self.cutoffSpinBox.setGeometry(QRect(140, 10, 65, 22))
        self.cutoffSpinBox.setDecimals(2)
        self.cutoffSpinBox.setMinimum(-15.000000000000000)
        self.cutoffSpinBox.setMaximum(-2.000000000000000)
        self.cutoffSpinBox.setSingleStep(0.100000000000000)
        self.cutoffSpinBox.setValue(-3.500000000000000)
        self.label_9 = QLabel(self.generalFrame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 10, 101, 16))
        self.colorMinusButton = QPushButton(self.generalFrame)
        self.colorMinusButton.setObjectName(u"colorMinusButton")
        self.colorMinusButton.setGeometry(QRect(90, 80, 100, 32))
        self.colorPlusButton = QPushButton(self.generalFrame)
        self.colorPlusButton.setObjectName(u"colorPlusButton")
        self.colorPlusButton.setGeometry(QRect(90, 40, 100, 32))
        self.label_11 = QLabel(self.generalFrame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 50, 58, 16))
        self.label_12 = QLabel(self.generalFrame)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 90, 58, 16))
        self.isoTab = QTabWidget(MOs_dialog)
        self.isoTab.setObjectName(u"isoTab")
        self.isoTab.setGeometry(QRect(210, 0, 171, 410))
        self.isosurfaceTab = QWidget()
        self.isosurfaceTab.setObjectName(u"isosurfaceTab")
        self.isosurfaceFrame = QFrame(self.isosurfaceTab)
        self.isosurfaceFrame.setObjectName(u"isosurfaceFrame")
        self.isosurfaceFrame.setGeometry(QRect(0, 0, 161, 240))
        self.isosurfaceFrame.setFrameShape(QFrame.StyledPanel)
        self.isosurfaceFrame.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.isosurfaceFrame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 91, 16))
        self.cubeBoxSizeSpinBox = QDoubleSpinBox(self.isosurfaceFrame)
        self.cubeBoxSizeSpinBox.setObjectName(u"cubeBoxSizeSpinBox")
        self.cubeBoxSizeSpinBox.setGeometry(QRect(90, 10, 65, 22))
        self.cubeBoxSizeSpinBox.setDecimals(1)
        self.cubeBoxSizeSpinBox.setMinimum(-1.900000000000000)
        self.cubeBoxSizeSpinBox.setMaximum(20.000000000000000)
        self.cubeBoxSizeSpinBox.setSingleStep(0.100000000000000)
        self.cubeBoxSizeSpinBox.setValue(0.000000000000000)
        self.checkBoxWireMesh = QCheckBox(self.isosurfaceFrame)
        self.checkBoxWireMesh.setObjectName(u"checkBoxWireMesh")
        self.checkBoxWireMesh.setGeometry(QRect(10, 130, 85, 20))
        self.toggleDisplayBoxButton = QPushButton(self.isosurfaceFrame)
        self.toggleDisplayBoxButton.setObjectName(u"toggleDisplayBoxButton")
        self.toggleDisplayBoxButton.setGeometry(QRect(10, 90, 140, 32))
        self.toggleDisplayBoxButton.setAutoDefault(False)
        self.displayMos = QPushButton(self.isosurfaceFrame)
        self.displayMos.setObjectName(u"displayMos")
        self.displayMos.setGeometry(QRect(10, 160, 140, 32))
        self.displayMos.setAutoDefault(False)
        self.isoValueSpinBox = QDoubleSpinBox(self.isosurfaceFrame)
        self.isoValueSpinBox.setObjectName(u"isoValueSpinBox")
        self.isoValueSpinBox.setGeometry(QRect(90, 70, 65, 22))
        self.isoValueSpinBox.setDecimals(4)
        self.isoValueSpinBox.setMinimum(0.000100000000000)
        self.isoValueSpinBox.setMaximum(1.000000000000000)
        self.isoValueSpinBox.setSingleStep(0.005000000000000)
        self.isoValueSpinBox.setValue(0.200000000000000)
        self.label_6 = QLabel(self.isosurfaceFrame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 70, 91, 16))
        self.label_5 = QLabel(self.isosurfaceFrame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 40, 91, 16))
        self.resolutionSpinBox = QDoubleSpinBox(self.isosurfaceFrame)
        self.resolutionSpinBox.setObjectName(u"resolutionSpinBox")
        self.resolutionSpinBox.setGeometry(QRect(90, 40, 65, 22))
        self.resolutionSpinBox.setDecimals(2)
        self.resolutionSpinBox.setMinimum(0.000000000000000)
        self.resolutionSpinBox.setMaximum(1.000000000000000)
        self.resolutionSpinBox.setSingleStep(0.050000000000000)
        self.resolutionSpinBox.setValue(0.500000000000000)
        self.recalculateOrbitalButton = QPushButton(self.isosurfaceFrame)
        self.recalculateOrbitalButton.setObjectName(u"recalculateOrbitalButton")
        self.recalculateOrbitalButton.setGeometry(QRect(9, 200, 141, 32))
        self.isoTab.addTab(self.isosurfaceTab, "")
        self.isolineTab = QWidget()
        self.isolineTab.setObjectName(u"isolineTab")
        self.isoLineFrame = QFrame(self.isolineTab)
        self.isoLineFrame.setObjectName(u"isoLineFrame")
        self.isoLineFrame.setGeometry(QRect(0, 0, 161, 380))
        self.isoLineFrame.setFrameShape(QFrame.StyledPanel)
        self.isoLineFrame.setFrameShadow(QFrame.Raised)
        self.numberLinesSpinBox = QSpinBox(self.isoLineFrame)
        self.numberLinesSpinBox.setObjectName(u"numberLinesSpinBox")
        self.numberLinesSpinBox.setGeometry(QRect(110, 10, 45, 22))
        self.numberLinesSpinBox.setMinimum(3)
        self.numberLinesSpinBox.setMaximum(20)
        self.numberLinesSpinBox.setValue(10)
        self.label_13 = QLabel(self.isoLineFrame)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 10, 70, 16))
        self.displayIsolinesButton = QPushButton(self.isoLineFrame)
        self.displayIsolinesButton.setObjectName(u"displayIsolinesButton")
        self.displayIsolinesButton.setGeometry(QRect(10, 70, 140, 32))
        self.label_14 = QLabel(self.isoLineFrame)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 40, 70, 16))
        self.isolineResolutionSpinBox = QDoubleSpinBox(self.isoLineFrame)
        self.isolineResolutionSpinBox.setObjectName(u"isolineResolutionSpinBox")
        self.isolineResolutionSpinBox.setGeometry(QRect(90, 40, 65, 22))
        self.isolineResolutionSpinBox.setMinimum(0.000000000000000)
        self.isolineResolutionSpinBox.setMaximum(1.000000000000000)
        self.isolineResolutionSpinBox.setSingleStep(0.050000000000000)
        self.isolineResolutionSpinBox.setValue(0.800000000000000)
        self.displayIsolineBorderButton = QPushButton(self.isoLineFrame)
        self.displayIsolineBorderButton.setObjectName(u"displayIsolineBorderButton")
        self.displayIsolineBorderButton.setGeometry(QRect(10, 100, 140, 32))
        self.planeFrame = QFrame(self.isoLineFrame)
        self.planeFrame.setObjectName(u"planeFrame")
        self.planeFrame.setGeometry(QRect(0, 130, 161, 111))
        self.planeFrame.setFrameShape(QFrame.StyledPanel)
        self.planeFrame.setFrameShadow(QFrame.Raised)
        self.resetButton = QPushButton(self.planeFrame)
        self.resetButton.setObjectName(u"resetButton")
        self.resetButton.setGeometry(QRect(10, 80, 140, 32))
        self.selectAtomsCheckBox = QCheckBox(self.planeFrame)
        self.selectAtomsCheckBox.setObjectName(u"selectAtomsCheckBox")
        self.selectAtomsCheckBox.setGeometry(QRect(10, 50, 140, 20))
        self.xAxisCheckBox = QCheckBox(self.planeFrame)
        self.xAxisCheckBox.setObjectName(u"xAxisCheckBox")
        self.xAxisCheckBox.setGeometry(QRect(10, 20, 30, 20))
        self.yAxisCheckBox = QCheckBox(self.planeFrame)
        self.yAxisCheckBox.setObjectName(u"yAxisCheckBox")
        self.yAxisCheckBox.setGeometry(QRect(60, 20, 30, 20))
        self.label_15 = QLabel(self.planeFrame)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 0, 91, 16))
        self.zAxisCheckBox = QCheckBox(self.planeFrame)
        self.zAxisCheckBox.setObjectName(u"zAxisCheckBox")
        self.zAxisCheckBox.setGeometry(QRect(110, 20, 30, 20))
        self.transformationFrame = QFrame(self.isoLineFrame)
        self.transformationFrame.setObjectName(u"transformationFrame")
        self.transformationFrame.setGeometry(QRect(0, 240, 161, 140))
        self.transformationFrame.setFrameShape(QFrame.StyledPanel)
        self.transformationFrame.setFrameShadow(QFrame.Raised)
        self.label_16 = QLabel(self.transformationFrame)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 50, 51, 16))
        self.translateCheckBox = QCheckBox(self.transformationFrame)
        self.translateCheckBox.setObjectName(u"translateCheckBox")
        self.translateCheckBox.setGeometry(QRect(70, 10, 80, 20))
        self.frame_3 = QFrame(self.transformationFrame)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(60, 70, 31, 20))
        self.frame_3.setStyleSheet(u"background-color: rgb(0, 255, 0)")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.greenSpinBox = QDoubleSpinBox(self.transformationFrame)
        self.greenSpinBox.setObjectName(u"greenSpinBox")
        self.greenSpinBox.setGeometry(QRect(100, 70, 53, 22))
        self.greenSpinBox.setMinimum(-180.000000000000000)
        self.greenSpinBox.setMaximum(180.000000000000000)
        self.rotateCheckBox = QCheckBox(self.transformationFrame)
        self.rotateCheckBox.setObjectName(u"rotateCheckBox")
        self.rotateCheckBox.setGeometry(QRect(10, 10, 60, 20))
        self.frame_2 = QFrame(self.transformationFrame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(60, 90, 31, 20))
        self.frame_2.setStyleSheet(u"background-color: rgb(0, 0, 255)")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.blueSpinBox = QDoubleSpinBox(self.transformationFrame)
        self.blueSpinBox.setObjectName(u"blueSpinBox")
        self.blueSpinBox.setGeometry(QRect(100, 90, 53, 22))
        self.blueSpinBox.setMinimum(-180.000000000000000)
        self.blueSpinBox.setMaximum(180.000000000000000)
        self.redSpinBox = QDoubleSpinBox(self.transformationFrame)
        self.redSpinBox.setObjectName(u"redSpinBox")
        self.redSpinBox.setGeometry(QRect(100, 50, 53, 22))
        self.redSpinBox.setMinimum(-180.000000000000000)
        self.redSpinBox.setMaximum(180.000000000000000)
        self.scaleCheckBox = QCheckBox(self.transformationFrame)
        self.scaleCheckBox.setObjectName(u"scaleCheckBox")
        self.scaleCheckBox.setGeometry(QRect(10, 30, 60, 20))
        self.frame = QFrame(self.transformationFrame)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(60, 50, 31, 20))
        self.frame.setStyleSheet(u"background-color: rgb(255, 0, 0)")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.displayAxesButton = QPushButton(self.transformationFrame)
        self.displayAxesButton.setObjectName(u"displayAxesButton")
        self.displayAxesButton.setGeometry(QRect(10, 110, 140, 32))
        self.isoTab.addTab(self.isolineTab, "")

        self.retranslateUi(MOs_dialog)

        self.isoTab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MOs_dialog)
    # setupUi

    def retranslateUi(self, MOs_dialog):
        MOs_dialog.setWindowTitle(QCoreApplication.translate("MOs_dialog", u"Orbitals", None))
        self.orbTypeLabel.setText(QCoreApplication.translate("MOs_dialog", u"Cartesian", None))
        self.label.setText(QCoreApplication.translate("MOs_dialog", u"Orbital type:", None))
        self.betaCheckBox.setText(QCoreApplication.translate("MOs_dialog", u"Beta", None))
        self.alphaCheckBox.setText(QCoreApplication.translate("MOs_dialog", u"Alpha", None))
        self.restrictedLabel.setText(QCoreApplication.translate("MOs_dialog", u"Restricted", None))
        self.label_3.setText(QCoreApplication.translate("MOs_dialog", u"Select Orbital:", None))
        self.label_7.setText(QCoreApplication.translate("MOs_dialog", u"Select Spin:", None))
        self.label_10.setText(QCoreApplication.translate("MOs_dialog", u"10 ^", None))
        self.label_9.setText(QCoreApplication.translate("MOs_dialog", u"Distance Cutoff:", None))
        self.colorMinusButton.setText(QCoreApplication.translate("MOs_dialog", u"Select", None))
        self.colorPlusButton.setText(QCoreApplication.translate("MOs_dialog", u"Select", None))
        self.label_11.setText(QCoreApplication.translate("MOs_dialog", u"Color +", None))
        self.label_12.setText(QCoreApplication.translate("MOs_dialog", u"Color -", None))
        self.label_4.setText(QCoreApplication.translate("MOs_dialog", u"Box Size", None))
        self.checkBoxWireMesh.setText(QCoreApplication.translate("MOs_dialog", u"Wire Mesh", None))
        self.toggleDisplayBoxButton.setText(QCoreApplication.translate("MOs_dialog", u"Display Box", None))
        self.displayMos.setText(QCoreApplication.translate("MOs_dialog", u"Display Orbital", None))
        self.label_6.setText(QCoreApplication.translate("MOs_dialog", u"Isovalue:", None))
        self.label_5.setText(QCoreApplication.translate("MOs_dialog", u"Resolution:", None))
        self.recalculateOrbitalButton.setText(QCoreApplication.translate("MOs_dialog", u"Recalculate Orbital", None))
        self.isoTab.setTabText(self.isoTab.indexOf(self.isosurfaceTab), QCoreApplication.translate("MOs_dialog", u"Isosurface", None))
        self.label_13.setText(QCoreApplication.translate("MOs_dialog", u"# of Lines:", None))
        self.displayIsolinesButton.setText(QCoreApplication.translate("MOs_dialog", u"Display Isolines", None))
        self.label_14.setText(QCoreApplication.translate("MOs_dialog", u"Resolution:", None))
        self.displayIsolineBorderButton.setText(QCoreApplication.translate("MOs_dialog", u"Display Border", None))
        self.resetButton.setText(QCoreApplication.translate("MOs_dialog", u"Reset Plane", None))
        self.selectAtomsCheckBox.setText(QCoreApplication.translate("MOs_dialog", u"Select Atoms Plane", None))
        self.xAxisCheckBox.setText(QCoreApplication.translate("MOs_dialog", u"x", None))
        self.yAxisCheckBox.setText(QCoreApplication.translate("MOs_dialog", u"y", None))
        self.label_15.setText(QCoreApplication.translate("MOs_dialog", u"Normal Vector:", None))
        self.zAxisCheckBox.setText(QCoreApplication.translate("MOs_dialog", u"z", None))
        self.label_16.setText(QCoreApplication.translate("MOs_dialog", u"Axis:", None))
        self.translateCheckBox.setText(QCoreApplication.translate("MOs_dialog", u"Translate", None))
        self.rotateCheckBox.setText(QCoreApplication.translate("MOs_dialog", u"Rotate", None))
        self.scaleCheckBox.setText(QCoreApplication.translate("MOs_dialog", u"Scale", None))
        self.displayAxesButton.setText(QCoreApplication.translate("MOs_dialog", u"Display Axes", None))
        self.isoTab.setTabText(self.isoTab.indexOf(self.isolineTab), QCoreApplication.translate("MOs_dialog", u"Isolines", None))
    # retranslateUi

