# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'measuring_tool.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QHeaderView,
    QLabel, QSizePolicy, QTableWidget, QTableWidgetItem,
    QWidget)

class Ui_measuring_tool(object):
    def setupUi(self, measuring_tool):
        if not measuring_tool.objectName():
            measuring_tool.setObjectName(u"measuring_tool")
        measuring_tool.resize(868, 542)
        measuring_tool.setMinimumSize(QSize(868, 542))
        measuring_tool.setMaximumSize(QSize(868, 542))
        self.info_text = QLabel(measuring_tool)
        self.info_text.setObjectName(u"info_text")
        self.info_text.setGeometry(QRect(10, 10, 371, 20))
        self.atom1 = QLabel(measuring_tool)
        self.atom1.setObjectName(u"atom1")
        self.atom1.setGeometry(QRect(10, 70, 21, 16))
        self.x1 = QLabel(measuring_tool)
        self.x1.setObjectName(u"x1")
        self.x1.setGeometry(QRect(10, 90, 50, 16))
        self.y1 = QLabel(measuring_tool)
        self.y1.setObjectName(u"y1")
        self.y1.setGeometry(QRect(70, 90, 50, 16))
        self.z1 = QLabel(measuring_tool)
        self.z1.setObjectName(u"z1")
        self.z1.setGeometry(QRect(130, 90, 50, 16))
        self.y2 = QLabel(measuring_tool)
        self.y2.setObjectName(u"y2")
        self.y2.setGeometry(QRect(70, 140, 50, 16))
        self.z2 = QLabel(measuring_tool)
        self.z2.setObjectName(u"z2")
        self.z2.setGeometry(QRect(130, 140, 50, 16))
        self.atom2 = QLabel(measuring_tool)
        self.atom2.setObjectName(u"atom2")
        self.atom2.setGeometry(QRect(10, 120, 21, 16))
        self.x2 = QLabel(measuring_tool)
        self.x2.setObjectName(u"x2")
        self.x2.setGeometry(QRect(10, 140, 50, 16))
        self.y3 = QLabel(measuring_tool)
        self.y3.setObjectName(u"y3")
        self.y3.setGeometry(QRect(70, 190, 50, 16))
        self.z3 = QLabel(measuring_tool)
        self.z3.setObjectName(u"z3")
        self.z3.setGeometry(QRect(130, 190, 50, 16))
        self.atom3 = QLabel(measuring_tool)
        self.atom3.setObjectName(u"atom3")
        self.atom3.setGeometry(QRect(10, 170, 21, 16))
        self.x3 = QLabel(measuring_tool)
        self.x3.setObjectName(u"x3")
        self.x3.setGeometry(QRect(10, 190, 50, 16))
        self.y4 = QLabel(measuring_tool)
        self.y4.setObjectName(u"y4")
        self.y4.setGeometry(QRect(70, 240, 50, 16))
        self.z4 = QLabel(measuring_tool)
        self.z4.setObjectName(u"z4")
        self.z4.setGeometry(QRect(130, 240, 50, 16))
        self.atom4 = QLabel(measuring_tool)
        self.atom4.setObjectName(u"atom4")
        self.atom4.setGeometry(QRect(10, 220, 21, 16))
        self.x4 = QLabel(measuring_tool)
        self.x4.setObjectName(u"x4")
        self.x4.setGeometry(QRect(10, 240, 50, 16))
        self.fix1 = QLabel(measuring_tool)
        self.fix1.setObjectName(u"fix1")
        self.fix1.setGeometry(QRect(190, 70, 71, 16))
        self.line = QFrame(measuring_tool)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(180, 70, 16, 191))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.atom1_label = QLabel(measuring_tool)
        self.atom1_label.setObjectName(u"atom1_label")
        self.atom1_label.setGeometry(QRect(40, 70, 16, 16))
        self.atom4_label = QLabel(measuring_tool)
        self.atom4_label.setObjectName(u"atom4_label")
        self.atom4_label.setGeometry(QRect(40, 220, 16, 16))
        self.atom3_label = QLabel(measuring_tool)
        self.atom3_label.setObjectName(u"atom3_label")
        self.atom3_label.setGeometry(QRect(40, 170, 16, 16))
        self.atom2_label = QLabel(measuring_tool)
        self.atom2_label.setObjectName(u"atom2_label")
        self.atom2_label.setGeometry(QRect(40, 120, 16, 16))
        self.fix3 = QLabel(measuring_tool)
        self.fix3.setObjectName(u"fix3")
        self.fix3.setGeometry(QRect(320, 70, 31, 16))
        self.fix2 = QLabel(measuring_tool)
        self.fix2.setObjectName(u"fix2")
        self.fix2.setGeometry(QRect(260, 70, 31, 16))
        self.fix4 = QLabel(measuring_tool)
        self.fix4.setObjectName(u"fix4")
        self.fix4.setGeometry(QRect(380, 70, 31, 16))
        self.d23 = QLabel(measuring_tool)
        self.d23.setObjectName(u"d23")
        self.d23.setGeometry(QRect(320, 90, 40, 16))
        self.d12 = QLabel(measuring_tool)
        self.d12.setObjectName(u"d12")
        self.d12.setGeometry(QRect(260, 90, 40, 16))
        self.d34 = QLabel(measuring_tool)
        self.d34.setObjectName(u"d34")
        self.d34.setGeometry(QRect(380, 90, 40, 16))
        self.fix5 = QLabel(measuring_tool)
        self.fix5.setObjectName(u"fix5")
        self.fix5.setGeometry(QRect(190, 90, 71, 16))
        self.a234 = QLabel(measuring_tool)
        self.a234.setObjectName(u"a234")
        self.a234.setGeometry(QRect(350, 160, 50, 30))
        self.fix3_2 = QLabel(measuring_tool)
        self.fix3_2.setObjectName(u"fix3_2")
        self.fix3_2.setGeometry(QRect(350, 140, 51, 30))
        self.fix5_2 = QLabel(measuring_tool)
        self.fix5_2.setObjectName(u"fix5_2")
        self.fix5_2.setGeometry(QRect(190, 160, 71, 30))
        self.a123 = QLabel(measuring_tool)
        self.a123.setObjectName(u"a123")
        self.a123.setGeometry(QRect(270, 160, 50, 30))
        self.fix2_2 = QLabel(measuring_tool)
        self.fix2_2.setObjectName(u"fix2_2")
        self.fix2_2.setGeometry(QRect(270, 140, 51, 30))
        self.fix1_2 = QLabel(measuring_tool)
        self.fix1_2.setObjectName(u"fix1_2")
        self.fix1_2.setGeometry(QRect(190, 140, 71, 30))
        self.d1234 = QLabel(measuring_tool)
        self.d1234.setObjectName(u"d1234")
        self.d1234.setGeometry(QRect(300, 240, 70, 16))
        self.fix1_3 = QLabel(measuring_tool)
        self.fix1_3.setObjectName(u"fix1_3")
        self.fix1_3.setGeometry(QRect(190, 220, 71, 16))
        self.fix2_3 = QLabel(measuring_tool)
        self.fix2_3.setObjectName(u"fix2_3")
        self.fix2_3.setGeometry(QRect(300, 220, 71, 16))
        self.fix5_3 = QLabel(measuring_tool)
        self.fix5_3.setObjectName(u"fix5_3")
        self.fix5_3.setGeometry(QRect(190, 240, 71, 16))
        self.fix_2 = QLabel(measuring_tool)
        self.fix_2.setObjectName(u"fix_2")
        self.fix_2.setGeometry(QRect(30, 50, 10, 16))
        self.fix_3 = QLabel(measuring_tool)
        self.fix_3.setObjectName(u"fix_3")
        self.fix_3.setGeometry(QRect(90, 50, 10, 16))
        self.fix_4 = QLabel(measuring_tool)
        self.fix_4.setObjectName(u"fix_4")
        self.fix_4.setGeometry(QRect(150, 50, 10, 16))
        self.fix = QLabel(measuring_tool)
        self.fix.setObjectName(u"fix")
        self.fix.setGeometry(QRect(10, 30, 111, 16))
        self.tableWidget = QTableWidget(measuring_tool)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 280, 411, 251))
        self.label = QLabel(measuring_tool)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(450, 280, 58, 16))
        self.tableWidget_2 = QTableWidget(measuring_tool)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(450, 320, 381, 192))

        self.retranslateUi(measuring_tool)

        QMetaObject.connectSlotsByName(measuring_tool)
    # setupUi

    def retranslateUi(self, measuring_tool):
        measuring_tool.setWindowTitle(QCoreApplication.translate("measuring_tool", u"Measurement Tool", None))
        self.info_text.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.atom1.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.x1.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.y1.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.z1.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.y2.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.z2.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.atom2.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.x2.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.y3.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.z3.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.atom3.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.x3.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.y4.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.z4.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.atom4.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.x4.setText(QCoreApplication.translate("measuring_tool", u"TextLabel", None))
        self.fix1.setText(QCoreApplication.translate("measuring_tool", u"Distances:", None))
        self.atom1_label.setText(QCoreApplication.translate("measuring_tool", u"<html><head/><body><p><span style=\" font-weight:700; color:#ff0000;\">1</span></p></body></html>", None))
        self.atom4_label.setText(QCoreApplication.translate("measuring_tool", u"<html><head/><body><p><span style=\" font-weight:700; color:#ffff00;\">4</span></p></body></html>", None))
        self.atom3_label.setText(QCoreApplication.translate("measuring_tool", u"<html><head/><body><p><span style=\" font-weight:700; color:#0000ff;\">3</span></p></body></html>", None))
        self.atom2_label.setText(QCoreApplication.translate("measuring_tool", u"<html><head/><body><p><span style=\" font-weight:700; color:#00ff00;\">2</span></p></body></html>", None))
        self.fix3.setText(QCoreApplication.translate("measuring_tool", u"2 - 3", None))
        self.fix2.setText(QCoreApplication.translate("measuring_tool", u"1 - 2", None))
        self.fix4.setText(QCoreApplication.translate("measuring_tool", u"3 - 4", None))
        self.d23.setText(QCoreApplication.translate("measuring_tool", u"d23", None))
        self.d12.setText(QCoreApplication.translate("measuring_tool", u"d12", None))
        self.d34.setText(QCoreApplication.translate("measuring_tool", u"d34", None))
        self.fix5.setText(QCoreApplication.translate("measuring_tool", u"in [\u00c5]", None))
        self.a234.setText(QCoreApplication.translate("measuring_tool", u"a234", None))
        self.fix3_2.setText(QCoreApplication.translate("measuring_tool", u"2 - 3 - 4", None))
        self.fix5_2.setText(QCoreApplication.translate("measuring_tool", u"in [\u00b0]", None))
        self.a123.setText(QCoreApplication.translate("measuring_tool", u"a123", None))
        self.fix2_2.setText(QCoreApplication.translate("measuring_tool", u"1 - 2 - 3", None))
        self.fix1_2.setText(QCoreApplication.translate("measuring_tool", u"Angles:", None))
        self.d1234.setText(QCoreApplication.translate("measuring_tool", u"d1234", None))
        self.fix1_3.setText(QCoreApplication.translate("measuring_tool", u"Dihedral:", None))
        self.fix2_3.setText(QCoreApplication.translate("measuring_tool", u"1 - 2 - 3 - 4", None))
        self.fix5_3.setText(QCoreApplication.translate("measuring_tool", u"in [\u00b0]", None))
        self.fix_2.setText(QCoreApplication.translate("measuring_tool", u"x", None))
        self.fix_3.setText(QCoreApplication.translate("measuring_tool", u"y", None))
        self.fix_4.setText(QCoreApplication.translate("measuring_tool", u"z", None))
        self.fix.setText(QCoreApplication.translate("measuring_tool", u"Coordinates in [\u00c5]:", None))
        self.label.setText(QCoreApplication.translate("measuring_tool", u"Angles:", None))
    # retranslateUi

