# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mos_dialog.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDialog, QDoubleSpinBox,
    QFrame, QHeaderView, QLabel, QPushButton,
    QSizePolicy, QTableWidget, QTableWidgetItem, QWidget)

class Ui_MOs_dialog(object):
    def setupUi(self, MOs_dialog):
        if not MOs_dialog.objectName():
            MOs_dialog.setObjectName(u"MOs_dialog")
        MOs_dialog.resize(425, 411)
        MOs_dialog.setMinimumSize(QSize(425, 317))
        self.label = QLabel(MOs_dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 81, 16))
        self.orbTypeLabel = QLabel(MOs_dialog)
        self.orbTypeLabel.setObjectName(u"orbTypeLabel")
        self.orbTypeLabel.setGeometry(QRect(90, 10, 101, 16))
        self.orbTypeLabel.setMaximumSize(QSize(101, 16))
        self.label_3 = QLabel(MOs_dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 50, 91, 16))
        self.orbitalSelector = QTableWidget(MOs_dialog)
        self.orbitalSelector.setObjectName(u"orbitalSelector")
        self.orbitalSelector.setGeometry(QRect(10, 70, 191, 331))
        self.label_7 = QLabel(MOs_dialog)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 30, 91, 16))
        self.alphaCheckBox = QCheckBox(MOs_dialog)
        self.alphaCheckBox.setObjectName(u"alphaCheckBox")
        self.alphaCheckBox.setGeometry(QRect(90, 30, 61, 21))
        self.betaCheckBox = QCheckBox(MOs_dialog)
        self.betaCheckBox.setObjectName(u"betaCheckBox")
        self.betaCheckBox.setGeometry(QRect(150, 30, 61, 20))
        self.restrictedLabel = QLabel(MOs_dialog)
        self.restrictedLabel.setObjectName(u"restrictedLabel")
        self.restrictedLabel.setGeometry(QRect(90, 30, 61, 16))
        self.frame_2 = QFrame(MOs_dialog)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(210, 0, 211, 171))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 91, 16))
        self.voxelSizeSpinBox = QDoubleSpinBox(self.frame_2)
        self.voxelSizeSpinBox.setObjectName(u"voxelSizeSpinBox")
        self.voxelSizeSpinBox.setGeometry(QRect(140, 60, 65, 22))
        self.voxelSizeSpinBox.setDecimals(2)
        self.voxelSizeSpinBox.setMinimum(0.050000000000000)
        self.voxelSizeSpinBox.setMaximum(1.000000000000000)
        self.voxelSizeSpinBox.setSingleStep(0.050000000000000)
        self.voxelSizeSpinBox.setValue(0.200000000000000)
        self.cubeBoxSizeSpinBox = QDoubleSpinBox(self.frame_2)
        self.cubeBoxSizeSpinBox.setObjectName(u"cubeBoxSizeSpinBox")
        self.cubeBoxSizeSpinBox.setGeometry(QRect(140, 7, 65, 22))
        self.cubeBoxSizeSpinBox.setDecimals(1)
        self.cubeBoxSizeSpinBox.setMinimum(-1.900000000000000)
        self.cubeBoxSizeSpinBox.setMaximum(20.000000000000000)
        self.cubeBoxSizeSpinBox.setSingleStep(0.100000000000000)
        self.cubeBoxSizeSpinBox.setValue(0.000000000000000)
        self.checkBoxWireMesh = QCheckBox(self.frame_2)
        self.checkBoxWireMesh.setObjectName(u"checkBoxWireMesh")
        self.checkBoxWireMesh.setGeometry(QRect(10, 120, 85, 20))
        self.label_5 = QLabel(self.frame_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 60, 91, 16))
        self.label_6 = QLabel(self.frame_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 80, 91, 16))
        self.toggleDisplayBoxButton = QPushButton(self.frame_2)
        self.toggleDisplayBoxButton.setObjectName(u"toggleDisplayBoxButton")
        self.toggleDisplayBoxButton.setGeometry(QRect(10, 30, 190, 32))
        self.toggleDisplayBoxButton.setAutoDefault(False)
        self.displayMos = QPushButton(self.frame_2)
        self.displayMos.setObjectName(u"displayMos")
        self.displayMos.setGeometry(QRect(10, 140, 190, 32))
        self.displayMos.setAutoDefault(False)
        self.isoValueSpinBox = QDoubleSpinBox(self.frame_2)
        self.isoValueSpinBox.setObjectName(u"isoValueSpinBox")
        self.isoValueSpinBox.setGeometry(QRect(140, 80, 65, 22))
        self.isoValueSpinBox.setDecimals(4)
        self.isoValueSpinBox.setMinimum(0.000100000000000)
        self.isoValueSpinBox.setMaximum(1.000000000000000)
        self.isoValueSpinBox.setSingleStep(0.005000000000000)
        self.isoValueSpinBox.setValue(0.200000000000000)
        self.label_9 = QLabel(self.frame_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 100, 101, 16))
        self.cutoffSpinBox = QDoubleSpinBox(self.frame_2)
        self.cutoffSpinBox.setObjectName(u"cutoffSpinBox")
        self.cutoffSpinBox.setGeometry(QRect(140, 100, 65, 22))
        self.cutoffSpinBox.setDecimals(2)
        self.cutoffSpinBox.setMinimum(-15.000000000000000)
        self.cutoffSpinBox.setMaximum(-2.000000000000000)
        self.cutoffSpinBox.setSingleStep(0.100000000000000)
        self.cutoffSpinBox.setValue(-3.500000000000000)
        self.label_10 = QLabel(self.frame_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(110, 100, 27, 16))
        self.frame_3 = QFrame(MOs_dialog)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(210, 170, 211, 91))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_12 = QLabel(self.frame_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 60, 58, 16))
        self.colorPlusButton = QPushButton(self.frame_3)
        self.colorPlusButton.setObjectName(u"colorPlusButton")
        self.colorPlusButton.setGeometry(QRect(90, 10, 100, 32))
        self.label_11 = QLabel(self.frame_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 20, 58, 16))
        self.colorMinusButton = QPushButton(self.frame_3)
        self.colorMinusButton.setObjectName(u"colorMinusButton")
        self.colorMinusButton.setGeometry(QRect(90, 50, 100, 32))
        self.frame = QFrame(MOs_dialog)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(210, 260, 211, 141))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 40, 131, 20))
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 80, 161, 20))
        self.exactCountLabel = QLabel(self.frame)
        self.exactCountLabel.setObjectName(u"exactCountLabel")
        self.exactCountLabel.setGeometry(QRect(10, 60, 131, 20))
        self.normalizationButton = QPushButton(self.frame)
        self.normalizationButton.setObjectName(u"normalizationButton")
        self.normalizationButton.setGeometry(QRect(10, 10, 190, 32))
        self.normalizationButton.setAutoDefault(False)
        self.calculatedCountLabel = QLabel(self.frame)
        self.calculatedCountLabel.setObjectName(u"calculatedCountLabel")
        self.calculatedCountLabel.setGeometry(QRect(10, 100, 131, 20))

        self.retranslateUi(MOs_dialog)

        QMetaObject.connectSlotsByName(MOs_dialog)
    # setupUi

    def retranslateUi(self, MOs_dialog):
        MOs_dialog.setWindowTitle(QCoreApplication.translate("MOs_dialog", u"Orbitals", None))
        self.label.setText(QCoreApplication.translate("MOs_dialog", u"Orbital type:", None))
        self.orbTypeLabel.setText(QCoreApplication.translate("MOs_dialog", u"Cartesian", None))
        self.label_3.setText(QCoreApplication.translate("MOs_dialog", u"Select Orbital:", None))
        self.label_7.setText(QCoreApplication.translate("MOs_dialog", u"Select Spin:", None))
        self.alphaCheckBox.setText(QCoreApplication.translate("MOs_dialog", u"Alpha", None))
        self.betaCheckBox.setText(QCoreApplication.translate("MOs_dialog", u"Beta", None))
        self.restrictedLabel.setText(QCoreApplication.translate("MOs_dialog", u"Restricted", None))
        self.label_4.setText(QCoreApplication.translate("MOs_dialog", u"Box Size", None))
        self.checkBoxWireMesh.setText(QCoreApplication.translate("MOs_dialog", u"Wire Mesh", None))
        self.label_5.setText(QCoreApplication.translate("MOs_dialog", u"Voxel Size", None))
        self.label_6.setText(QCoreApplication.translate("MOs_dialog", u"Isovalue", None))
        self.toggleDisplayBoxButton.setText(QCoreApplication.translate("MOs_dialog", u"Display Box", None))
        self.displayMos.setText(QCoreApplication.translate("MOs_dialog", u"Display Orbital", None))
        self.label_9.setText(QCoreApplication.translate("MOs_dialog", u"Distance Cutoff:", None))
        self.label_10.setText(QCoreApplication.translate("MOs_dialog", u"10 ^", None))
        self.label_12.setText(QCoreApplication.translate("MOs_dialog", u"Color -", None))
        self.colorPlusButton.setText(QCoreApplication.translate("MOs_dialog", u"Select", None))
        self.label_11.setText(QCoreApplication.translate("MOs_dialog", u"Color +", None))
        self.colorMinusButton.setText(QCoreApplication.translate("MOs_dialog", u"Select", None))
        self.label_2.setText(QCoreApplication.translate("MOs_dialog", u"Exact Electroncount:", None))
        self.label_8.setText(QCoreApplication.translate("MOs_dialog", u"Calculated Electroncount:", None))
        self.exactCountLabel.setText("")
        self.normalizationButton.setText(QCoreApplication.translate("MOs_dialog", u"Check Normalization", None))
        self.calculatedCountLabel.setText("")
    # retranslateUi
